# Generated by Django 2.0.6 on 2018-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('intTime', models.DateTimeField(auto_now_add=True)),
                ('updTime', models.DateTimeField(auto_now=True)),
                ('userId', models.IntegerField(default=0)),
            ],
        ),
    ]
